# Managed by workstation-setup.
[Sleep]
AllowSuspend=yes
AllowHibernation=yes
AllowSuspendThenHibernate=yes
SuspendState=mem
MemorySleepMode=deep
HibernateMode=platform
HibernateDelaySec=2h
HibernateOnACPower=yes
